USE `test_db`;
DROP function IF EXISTS `ASAL_KONTROL`;

DELIMITER $$
USE `test_db`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `ASAL_KONTROL`(PAR_SAYI int) RETURNS int(11)
BEGIN
/*
Sayinin asal olup olmadigini doner,
 Asalsa 1 degilse 0 doner
*/
declare SAYAC,SINIR int;
SET SAYAC = 2;
SET SINIR =CAST(SQRT(PAR_SAYI) AS UNSIGNED);
myLOOP : LOOP
IF  SAYAC>SINIR THEN
LEAVE  myLOOP;
END IF;
IF  MOD(PAR_SAYI,SAYAC)=0 THEN
RETURN 0;
END IF;

SET SAYAC = SAYAC + 1;
ITERATE myLOOP;
END LOOP myLOOP;
RETURN 1;
END$$

DELIMITER ;



select test_db.ASAL_KONTROL(37);
